"""migration

Revision ID: d1f28027789c
Revises: 
Create Date: 2021-02-01 22:04:46.812707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f28027789c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('user_image', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.Column('followed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follow_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_body', sa.String(length=250), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recepient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recepient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_body', sa.String(length=250), nullable=False),
    sa.Column('post_image', sa.Text(), nullable=False),
    sa.Column('post_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment_body', sa.String(length=250), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('to_be_notified_id', sa.Integer(), nullable=True),
    sa.Column('action_by_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('is_like', sa.Integer(), nullable=True),
    sa.Column('is_comment', sa.Integer(), nullable=True),
    sa.Column('is_follow', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['to_be_notified_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('post')
    op.drop_table('messages')
    op.drop_table('follows')
    op.drop_table('user')
    # ### end Alembic commands ###
